services:
   subgen:
      container_name: subgen
      tty: true
      build: .
      environment:
         - "OPENAI_BASE_URL=https://api.openai.com/v1"
         - "OPENAI_API_KEY=${OPENAI_API_KEY}"
         - "OPENAI_TRANSCRIPTION_MODEL=whisper-1"
         - "OPENAI_TRANSLATION_MODEL=whisper-1"
         - "OPENAI_AUDIO_FORMAT=wav"
         - "OPENAI_AUDIO_BITRATE=64k"
         - "PROCESS_ADDED_MEDIA=True"
         - "PROCESS_MEDIA_ON_PLAY=False"
         - "SUBTITLE_LANGUAGE_NAME=aa"
         - "SKIP_IF_INTERNAL_SUBTITLES_LANGUAGE=eng"
         - "PLEX_TOKEN=plextoken"
         - "PLEX_SERVER=http://plexserver:32400"
         - "JELLYFIN_TOKEN=token here"
         - "JELLYFIN_SERVER=http://jellyfin:8096"
         - "WEBHOOK_PORT=9000"
         - "CONCURRENT_TRANSCRIPTIONS=2"
         - "DEBUG=True"
         - "USE_PATH_MAPPING=False"
         - "PATH_MAPPING_FROM=/tv"
         - "PATH_MAPPING_TO=/Volumes/TV"
         - "APPEND=False"
         - "LRC_FOR_AUDIO_FILES=True"
      volumes:
         - "${TV}:/tv"
         - "${MOVIES}:/movies"
      ports:
         - "9000:9000"
